// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RegisterRequestRole.
const (
	RegisterRequestRoleEmployee  RegisterRequestRole = "employee"
	RegisterRequestRoleModerator RegisterRequestRole = "moderator"
)

// Defines values for UserResponseRole.
const (
	UserResponseRoleEmployee  UserResponseRole = "employee"
	UserResponseRoleModerator UserResponseRole = "moderator"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     RegisterRequestRole `json:"role"`
}

// RegisterRequestRole defines model for RegisterRequest.Role.
type RegisterRequestRole string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	Token *string `json:"token,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Id    *openapi_types.UUID  `json:"id,omitempty"`
	Role  *UserResponseRole    `json:"role,omitempty"`
}

// UserResponseRole defines model for UserResponse.Role.
type UserResponseRole string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest
